name: Scrape

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 23 * * *"  # Runs every day at 6 PM EST

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 os tabula pandas

      - name: Run scraper
        run: python scraper/scrape.py

      - name: Commit and push if changed
        run: |-
          git config --global user.name "eviction_notice_bot"
          git config --global user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "New scheduled evictions data available: ${timestamp}" || exit 0
          git push
